cat(paste("Years BR Data:", n.band.years, sep = " "))
cat('\n')
cat(paste("Number of Individuals in BR Data:", nbandind, sep = " "))
cat('\n')
cat(paste("Additional Years of Total Harvest Data in SS:", n.years.totharv))
cat('\n')
cat(paste("Years WSR Data:", n.years.telem, sep = " "))
cat('\n')
cat(paste("Number of Individuals in WSR Data:", ntelemind, sep = " "))